// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OTPRepository is an autogenerated mock type for the OTPRepository type
type OTPRepository struct {
	mock.Mock
}

// DeleteOTP provides a mock function with given fields: email, purpose
func (_m *OTPRepository) DeleteOTP(email string, purpose string) error {
	ret := _m.Called(email, purpose)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOTP provides a mock function with given fields: email, purpose
func (_m *OTPRepository) GetOTP(email string, purpose string) (string, error) {
	ret := _m.Called(email, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, purpose)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, purpose)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, purpose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOTP provides a mock function with given fields: email, purpose, code, expiration
func (_m *OTPRepository) SaveOTP(email string, purpose string, code string, expiration time.Duration) error {
	ret := _m.Called(email, purpose, code, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SaveOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, time.Duration) error); ok {
		r0 = rf(email, purpose, code, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOTPRepository creates a new instance of OTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPRepository {
	mock := &OTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
